name: My first Workflow

#trigger
on:
  push:
    branches:
      - 'v[0-9].[0-9]'

#jobs in the workflow
jobs:
#job name
  my-first-workflow:
    #os that this workflow will be running on
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}
    #list of steps to perform task
    steps: 
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
      # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
                {  
                "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "blocks": [
                     {
                      "type": "header",
                      "text": 
                        {
                          "type": "plain_text",
                          "text": "DipSA55 CI/CD Assignment Submission",
                          "emoji": true
                        }
                      },
                      {
                          "type": "section",
                          "fields": [
                              {
                                  "type": "mrkdwn",
                                  "text": "*Name:*\n XIE WENWEN"
                              },
                              {
                                  "type": "mrkdwn",
                                  "text": "Matriculation:*\nA0265059X"
                              }
                          ]
                      },
                      {
                          "type": "section",
                          "fields": [
                              {
                                  "type": "mrkdwn",
                                  "text": "*Email:*\n e1045734@u.nus.edu"
                              },
                              {
                                  "type": "mrkdwn",
                                  "text": "Repositary:*\nhttps://github.com/xiewenwen95/CICD-Assignment.git"
                              }
                          ]
                      },
                      {
                          "type": "section",
                          "fields": [
                              {
                                  "type": "mrkdwn",
                                  "text": "*Deployment:*\nhttps://brief-cow-production.up.railway.app/"
                              }
                            ]
                          },
                              {
                                 "type": "section",
                                 "text": {
                                  "type": "mrkdwn",
                                  "text": "<https://brief-cow-production.up.railway.app/|Open Application>"
                              }
                          }
                      ]
                }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_SUB }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
