name: My first Workflow

#trigger
on:
  push:
    branches:
      - 'v**.+'

#jobs in the workflow
jobs:
#job name
  my-first-workflow:
    #os that this workflow will be running on
    runs-on: ubuntu-latest
    #list of steps to perform task
    steps: 
    - name: basic test
      run: echo "the current time and date in Github is $(date)"
