name: My first Workflow

#trigger
on:
  push:
    branches:
      - 'v[0-9].[0-9]'

#jobs in the workflow
jobs:
#job name
  my-first-workflow:
    #os that this workflow will be running on
    runs-on: ubuntu-latest
    #list of steps to perform task
    steps: 
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
      # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
                {
                  "text": {
                        "blocks": [
                        {
                          "type": "header",
                          "text": {
                            "type": "plain_text",
                            "text": "DipSA55 CI/CD Assignment Submission"
                          }
                        },
                        {
                          "type": "section",
                          "fields": [
                            {
                              "type": "mrkdwn",
                              "text": "*Name*"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Metriculation*"
                            },
                            {
                              "type": "plain_text",
                              "text": "X"
                            },
                            {
                              "type": "plain_text",
                              "text": "X"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Email*"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Repository*"
                            },
                            {
                              "type": "plain_text",
                              "text": "X"
                            },
                            {
                              "type": "plain_text",
                              "text": "X"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "*Deployment* \n X"
                            }
                          ]
                        }
                      ]
                  }
                }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
