name: Release and deploy go-fortune

on: 
  push:
    branches:
      - 'v[0-9].[0-9]'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "README.md"
          tag: repo
          token: ${{ secrets.GITHUB_TOKEN }}
