name: Release and deploy go-fortune

on:
 push
  branches:
  - "release/.+"

jobs:
  release-and-delpoy:
    runs-on: ubuntu-latest
    steps:
    - name: branch name
      run: echo "branch name - ${{ github.ref_name }}"
    - name: Check out the current repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: List my current dicrectory after checkout
      run: ls -la
